-- =========================================
-- USER_TBL 데이터
-- =========================================
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('jihoLee1', 'Qw3rtyJiho', '이지호', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('soominKim22', 'So0min2023', '김수민', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('minjun98', 'MnJ98pass', '민준', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('jiwonPark3', 'Jiw0nPark', '박지원', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('hyunwoo87', 'Hy3nw0087', '현우', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('seoyeon22', 'Se0yeon22', '서연', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('yujinChoi5', 'YujnC123', '최유진', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('jisooKang7', 'JiS00kang', '강지수', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('hyejin460', 'Hy3Jin460', '혜진', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('daeunLee9', 'DaeUnLee7', '이대은', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('taeyoung21', 'TaeY0ung21', '태영', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('sungminH', 'SungMnH', '성민', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('eunjiPark', 'EunJiPark1', '박은지', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('nayeon99', 'Nay3on99', '나연', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('junhoK', 'Junh0K', '준호', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('haeunS', 'HaeUnS', '하은', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('minseok42', 'MinSe0k42', '민석', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('sooyoungY', 'So0Y0ung', '수영', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('yoonseoK', 'Yoon3oK77', '윤서', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('minjiPark', 'MnJiPark2', '민지', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('chaeyoung10', 'ChaeY0ung10', '채영', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('seungminB', 'SeungMnB', '승민', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('jiminH', 'JiMnH2024', '지민', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('hyunjin99', 'Hyunj1n99', '현진', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('jungsuPark', 'JungSuP', '정수', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('yejinK', 'YeJ1nKG', '예진', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('donghyunW', 'D0ngHyunW', '동현', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('seunghee99', 'SeungH33', '승희', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('kyungsoo', 'KyunGsoo7', '경수', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('haneulR', 'HaneulR2', '하늘', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('minsuPark', 'M1nSuPark', '민수', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('yunaKim', 'YuNaKim5', '유나', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('yeonwoo01', 'Ye0nW00', '연우', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('hyeonwoo', 'Hy3onW00', '현우', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('jaehoLee', 'JaeH0Lee', '재호', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('seunghyun', 'Seunghyun8', '승현', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('boraPark', 'BoraPark33', '보라', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('hyojinK', 'HyoJ1nK', '효진', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('siwoo22', 'SiW0022', '시우', NULL);
INSERT INTO USER_TBL (id, password, nickname, profile_image) VALUES ('juhyun21', 'JuHyun21', '주현', NULL);

-- =========================================
-- POST_TBL 임시 데이터
-- =========================================
INSERT INTO POST_TBL (title, user_seq) VALUES ('서울에서 꼭 가봐야 할 맛집 추천', 1);
INSERT INTO POST_TBL (title, user_seq) VALUES ('이번 주말에 다녀온 카페 탐방기', 2);
INSERT INTO POST_TBL (title, user_seq) VALUES ('강릉 바다 근처 숨은 맛집 후기', 3);
INSERT INTO POST_TBL (title, user_seq) VALUES ('데이트하기 좋은 예쁜 공원 소개', 4);
INSERT INTO POST_TBL (title, user_seq) VALUES ('부산 여행 중 먹은 해산물 맛집', 5);
INSERT INTO POST_TBL (title, user_seq) VALUES ('친구들과 다녀온 힙한 카페 모음', 6);
INSERT INTO POST_TBL (title, user_seq) VALUES ('연남동 골목길 소소한 맛집 이야기', 7);
INSERT INTO POST_TBL (title, user_seq) VALUES ('주말 나들이, 서울 근교 드라이브 코스', 8);
INSERT INTO POST_TBL (title, user_seq) VALUES ('맛있는 디저트를 즐길 수 있는 카페', 9);
INSERT INTO POST_TBL (title, user_seq) VALUES ('이번 여행에서 추천하고 싶은 숨은 명소', 10);
INSERT INTO POST_TBL (title, user_seq) VALUES ('신사동 가로수길 핫플레이스 탐방', 11);
INSERT INTO POST_TBL (title, user_seq) VALUES ('강남역 근처 저렴하고 맛있는 식당 추천', 12);
INSERT INTO POST_TBL (title, user_seq) VALUES ('주말 브런치 즐기기 좋은 카페', 13);
INSERT INTO POST_TBL (title, user_seq) VALUES ('여름철 시원하게 즐기는 디저트 맛집', 14);
INSERT INTO POST_TBL (title, user_seq) VALUES ('아이와 함께 가기 좋은 공원 소개', 15);
INSERT INTO POST_TBL (title, user_seq) VALUES ('서울 근교 드라이브하며 들른 맛집', 16);
INSERT INTO POST_TBL (title, user_seq) VALUES ('가을 단풍 시즌 추천 여행지', 17);
INSERT INTO POST_TBL (title, user_seq) VALUES ('혼자서도 편하게 즐길 수 있는 카페', 18);
INSERT INTO POST_TBL (title, user_seq) VALUES ('데이트할 때 가기 좋은 레스토랑', 19);
INSERT INTO POST_TBL (title, user_seq) VALUES ('강릉에서 맛본 해물파전 후기', 20);
INSERT INTO POST_TBL (title, user_seq) VALUES ('주말 여행 코스 추천', 21);
INSERT INTO POST_TBL (title, user_seq) VALUES ('서울 맛집 골목길 탐방기', 22);
INSERT INTO POST_TBL (title, user_seq) VALUES ('친구와 함께한 카페 투어', 23);
INSERT INTO POST_TBL (title, user_seq) VALUES ('이번 달 꼭 가야 할 전시회 소개', 24);
INSERT INTO POST_TBL (title, user_seq) VALUES ('서울 근교 드라이브 코스와 맛집', 25);
INSERT INTO POST_TBL (title, user_seq) VALUES ('연남동 숨은 디저트 맛집', 26);
INSERT INTO POST_TBL (title, user_seq) VALUES ('부산 해운대 근처 추천 카페', 27);
INSERT INTO POST_TBL (title, user_seq) VALUES ('친구와 다녀온 브런치 카페', 28);
INSERT INTO POST_TBL (title, user_seq) VALUES ('서울 야경 보기 좋은 장소 추천', 29);
INSERT INTO POST_TBL (title, user_seq) VALUES ('이번 주말 방문할만한 맛집', 30);
INSERT INTO POST_TBL (title, user_seq) VALUES ('혼자서도 편하게 즐기는 브런치', 31);
INSERT INTO POST_TBL (title, user_seq) VALUES ('데이트하면서 가기 좋은 카페 리스트', 32);
INSERT INTO POST_TBL (title, user_seq) VALUES ('서울 근교 산책하며 들른 맛집', 33);
INSERT INTO POST_TBL (title, user_seq) VALUES ('강남 핫플레이스 탐방기', 34);
INSERT INTO POST_TBL (title, user_seq) VALUES ('이번 달 추천 여행지 모음', 35);
INSERT INTO POST_TBL (title, user_seq) VALUES ('친구와 가기 좋은 카페 소개', 36);
INSERT INTO POST_TBL (title, user_seq) VALUES ('서울 숨은 맛집 리뷰', 37);
INSERT INTO POST_TBL (title, user_seq) VALUES ('주말에 방문할만한 디저트 카페', 38);

-- =========================================
-- POST_CONTENT_TBL 임시 데이터
-- =========================================
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (1,'IMAGE','/dummy-images/Dummy_Img(1).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (1,'LOCATION','울프강스테이크하우스',37.52439983131448,127.04141558950498,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (1,'TEXT','서울에서 최근 다녀온 맛집입니다. 내부 인테리어도 깔끔하고 분위기가 아늑해 식사 내내 편안했습니다. 특히 대표 메뉴인 스테이크는 육즙이 살아있고 맛이 풍부했습니다. 다음에 친구와 함께 다시 방문하고 싶네요.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (2,'IMAGE','/dummy-images/Dummy_Img(2).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (2,'LOCATION','한강대교',37.5158498807079,126.957644637952,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (2,'TEXT','이번 주말에 다녀온 카페 후기입니다. 인테리어가 아기자기하고 포토존이 많아 사진 찍기에 좋습니다. 커피 맛도 훌륭하며, 디저트 메뉴도 추천할 만합니다. 친구들과 여유롭게 시간을 보내기에 딱 좋습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (3,'IMAGE','/dummy-images/Dummy_Img(3).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (3,'LOCATION','강릉중앙시장',37.754025117657804,128.8986237900098,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (3,'TEXT','강릉 바닷가 근처의 숨은 맛집을 다녀왔습니다. 신선한 해산물 요리가 일품이며, 바다를 바라보며 식사할 수 있어 힐링됩니다. 위치가 조금 외진 곳이지만 충분히 방문할 가치가 있으며, 다음 여행에도 꼭 들르고 싶은 곳입니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (4,'IMAGE','/dummy-images/Dummy_Img(4).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (4,'LOCATION','서울대공원',37.436451567677,127.01389825362084,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (4,'TEXT','데이트하기 좋은 예쁜 공원을 다녀왔습니다. 산책로가 잘 정비되어 있고 곳곳에 벤치와 포토존이 있어 여유롭게 즐길 수 있습니다. 특히 일몰 시간대에 방문하면 풍경이 더욱 아름다워 사진 찍기에도 적합합니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (5,'IMAGE','/dummy-images/Dummy_Img(5).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (5,'LOCATION','어부의술상',35.16874630455375,129.19713890883997,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (5,'TEXT','부산 여행 중 다녀온 해산물 맛집입니다. 신선한 재료와 푸짐한 양으로 만족스러웠습니다. 특히 해물파전과 회가 인기 메뉴로 맛있으며, 내부 분위기도 아늑해 친구 또는 연인과 방문하기 좋습니다. 재방문 의사도 충분합니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (6,'IMAGE','/dummy-images/Dummy_Img(6).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (6,'LOCATION','스태픽스',37.5774769385374,126.967908167278,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (6,'TEXT','서울의 한적한 골목에 위치한 작은 카페를 방문했습니다. 커피와 디저트 모두 훌륭했고, 무엇보다 조용한 분위기에서 독서를 즐기기에 최적의 장소였습니다. 혼자만의 시간을 보내기에 완벽한 곳이었습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (7,'IMAGE','/dummy-images/Dummy_Img(7).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (7,'LOCATION','비비비당',35.162550535259946,129.1850134393127,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (7,'TEXT','주말에 가족과 함께 다녀온 전통 찻집입니다. 고즈넉한 분위기와 함께 전통 다과를 즐길 수 있어 좋았습니다. 특히 차 종류가 다양하고, 직원분들의 서비스도 친절하여 기분 좋은 시간을 보냈습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (8,'IMAGE','/dummy-images/Dummy_Img(8).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (8,'LOCATION','강동그린웨이 가족캠핑장',37.53587362320591,127.1540881919585,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (8,'TEXT','서울 근교에 위치한 캠핑장에 다녀왔습니다. 자연 속에서 힐링하며 바베큐를 즐길 수 있어 좋았습니다. 시설도 잘 갖추어져 있어 편안하게 지낼 수 있었고, 다음에는 친구들과 함께 다시 방문하고 싶습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (9,'IMAGE','/dummy-images/Dummy_Img(9).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (9,'LOCATION','광장시장',37.570033672535104,126.9989416227693,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (9,'TEXT','주말에 방문한 전통 시장입니다. 다양한 먹거리가 가득하고, 상인분들의 친절한 서비스가 인상적이었습니다. 특히 길거리 음식이 맛있어서 여러 가지를 시도해보았는데 모두 만족스러웠습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (10,'IMAGE','/dummy-images/Dummy_Img(10).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (10,'LOCATION','해운대해수욕장',35.1585232170784,129.159854668484,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (10,'TEXT','부산의 한적한 바닷가를 산책했습니다. 시원한 바닷바람과 함께 여유로운 시간을 보낼 수 있어 좋았습니다. 주변에 카페도 있어 음료를 즐기며 바다를 감상할 수 있어 힐링이 되었습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (11,'IMAGE','/dummy-images/Dummy_Img(11).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (11,'LOCATION','아웃백스테이크하우스 강남점',37.507109947772356,127.02370583236541,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (11,'TEXT','서울에서 최근 다녀온 맛집입니다. 내부 인테리어도 깔끔하고 분위기가 아늑해 식사 내내 편안했습니다. 특히 대표 메뉴인 스테이크는 육즙이 살아있고 맛이 풍부했습니다. 다음에 친구와 함께 다시 방문하고 싶네요.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (12,'IMAGE','/dummy-images/Dummy_Img(12).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (12,'LOCATION','기욤 청담점',37.524317115354286,127.04090986917596,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (12,'TEXT','이번 주말에 다녀온 카페 후기입니다. 인테리어가 아기자기하고 포토존이 많아 사진 찍기에 좋습니다. 커피 맛도 훌륭하며, 디저트 메뉴도 추천할 만합니다. 친구들과 여유롭게 시간을 보내기에 딱 좋습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (13,'IMAGE','/dummy-images/Dummy_Img(13).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (13,'LOCATION','바다회사랑',37.5604116806539,126.921063142318,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (13,'TEXT','강릉 바닷가 근처의 숨은 맛집을 다녀왔습니다. 신선한 해산물 요리가 일품이며, 바다를 바라보며 식사할 수 있어 힐링됩니다. 위치가 조금 외진 곳이지만 충분히 방문할 가치가 있으며, 다음 여행에도 꼭 들르고 싶은 곳입니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (14,'IMAGE','/dummy-images/Dummy_Img(14).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (14,'LOCATION','서울숲',37.5443222301513,127.037617759165,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (14,'TEXT','데이트하기 좋은 예쁜 공원을 다녀왔습니다. 산책로가 잘 정비되어 있고 곳곳에 벤치와 포토존이 있어 여유롭게 즐길 수 있습니다. 특히 일몰 시간대에 방문하면 풍경이 더욱 아름다워 사진 찍기에도 적합합니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (15,'IMAGE','/dummy-images/Dummy_Img(15).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (15,'LOCATION','이재모피자 본점',35.10204215079571,129.030747190728,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (15,'TEXT','부산 여행 중 다녀온 해산물 맛집입니다. 신선한 재료와 푸짐한 양으로 만족스러웠습니다. 특히 해물파전과 회가 인기 메뉴로 맛있으며, 내부 분위기도 아늑해 친구 또는 연인과 방문하기 좋습니다. 재방문 의사도 충분합니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (16,'IMAGE','/dummy-images/Dummy_Img(16).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (16,'LOCATION','대충유원지',37.5587425645618,126.920363197604,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (16,'TEXT','서울의 한적한 골목에 위치한 작은 카페를 방문했습니다. 커피와 디저트 모두 훌륭했고, 무엇보다 조용한 분위기에서 독서를 즐기기에 최적의 장소였습니다. 혼자만의 시간을 보내기에 완벽한 곳이었습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (17,'IMAGE','/dummy-images/Dummy_Img(17).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (17,'LOCATION','수연산방',37.59507217364634,126.99483655959386,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (17,'TEXT','주말에 가족과 함께 다녀온 전통 찻집입니다. 고즈넉한 분위기와 함께 전통 다과를 즐길 수 있어 좋았습니다. 특히 차 종류가 다양하고, 직원분들의 서비스도 친절하여 기분 좋은 시간을 보냈습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (18,'IMAGE','/dummy-images/Dummy_Img(18).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (18,'LOCATION','난지캠핑장',37.5699951008368,126.872166235201,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (18,'TEXT','서울 근교에 위치한 캠핑장에 다녀왔습니다. 자연 속에서 힐링하며 바베큐를 즐길 수 있어 좋았습니다. 시설도 잘 갖추어져 있어 편안하게 지낼 수 있었고, 다음에는 친구들과 함께 다시 방문하고 싶습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (19,'LOCATION','자갈치시장',35.09661988021089,129.03057978534403,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (19,'TEXT','주말에 방문한 전통 시장입니다. 다양한 먹거리가 가득하고, 상인분들의 친절한 서비스가 인상적이었습니다. 특히 길거리 음식이 맛있어서 여러 가지를 시도해보았는데 모두 만족스러웠습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (19,'IMAGE','/dummy-images/Dummy_Img(19).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (20,'IMAGE','/dummy-images/Dummy_Img(20).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (20,'TEXT','부산의 한적한 바닷가를 산책했습니다. 시원한 바닷바람과 함께 여유로운 시간을 보낼 수 있어 좋았습니다. 주변에 카페도 있어 음료를 즐기며 바다를 감상할 수 있어 힐링이 되었습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (20,'LOCATION','광안리해수욕장',35.1531932736837,129.118976093583,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (21,'IMAGE','/dummy-images/Dummy_Img(21).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (21,'TEXT','서울에서 최근 다녀온 맛집입니다. 내부 인테리어도 깔끔하고 분위기가 아늑해 식사 내내 편안했습니다. 특히 대표 메뉴인 스테이크는 육즙이 살아있고 맛이 풍부했습니다. 다음에 친구와 함께 다시 방문하고 싶네요.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (21,'LOCATION','정원레스토랑 어반가든',37.5674329910375,126.969202859743,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (22,'IMAGE','/dummy-images/Dummy_Img(22).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (22,'TEXT','이번 주말에 다녀온 카페 후기입니다. 인테리어가 아기자기하고 포토존이 많아 사진 찍기에 좋습니다. 커피 맛도 훌륭하며, 디저트 메뉴도 추천할 만합니다. 친구들과 여유롭게 시간을 보내기에 딱 좋습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (22,'LOCATION','주말카페',37.621179299210496,127.89496909375454,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (23,'IMAGE','/dummy-images/Dummy_Img(23).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (23,'TEXT','강릉 바닷가 근처의 숨은 맛집을 다녀왔습니다. 신선한 해산물 요리가 일품이며, 바다를 바라보며 식사할 수 있어 힐링됩니다. 위치가 조금 외진 곳이지만 충분히 방문할 가치가 있으며, 다음 여행에도 꼭 들르고 싶은 곳입니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (23,'LOCATION','아바이회국수',37.770049039186574,128.90544541218512,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (24,'IMAGE','/dummy-images/Dummy_Img(24).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (24,'TEXT','데이트하기 좋은 예쁜 공원을 다녀왔습니다. 산책로가 잘 정비되어 있고 곳곳에 벤치와 포토존이 있어 여유롭게 즐길 수 있습니다. 특히 일몰 시간대에 방문하면 풍경이 더욱 아름다워 사진 찍기에도 적합합니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (24,'LOCATION','낙산공원',37.58056966858,127.007521763748,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (25,'IMAGE','/dummy-images/Dummy_Img(25).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (25,'TEXT','부산 여행 중 다녀온 해산물 맛집입니다. 신선한 재료와 푸짐한 양으로 만족스러웠습니다. 특히 해물파전과 회가 인기 메뉴로 맛있으며, 내부 분위기도 아늑해 친구 또는 연인과 방문하기 좋습니다. 재방문 의사도 충분합니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (25,'LOCATION','해선재',37.55302743739297,126.6533051748557,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (26,'IMAGE','/dummy-images/Dummy_Img(26).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (26,'TEXT','서울의 한적한 골목에 위치한 작은 카페를 방문했습니다. 커피와 디저트 모두 훌륭했고, 무엇보다 조용한 분위기에서 독서를 즐기기에 최적의 장소였습니다. 혼자만의 시간을 보내기에 완벽한 곳이었습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (26,'LOCATION','서울숲카페거리',37.5464440372535,127.043028992489,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (27,'IMAGE','/dummy-images/Dummy_Img(27).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (27,'TEXT','주말에 가족과 함께 다녀온 전통 찻집입니다. 고즈넉한 분위기와 함께 전통 다과를 즐길 수 있어 좋았습니다. 특히 차 종류가 다양하고, 직원분들의 서비스도 친절하여 기분 좋은 시간을 보냈습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (27,'LOCATION','루치아의 뜰',36.45380108151801,127.12378364488573,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (28,'IMAGE','/dummy-images/Dummy_Img(28).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (28,'TEXT','서울 근교에 위치한 캠핑장에 다녀왔습니다. 자연 속에서 힐링하며 바베큐를 즐길 수 있어 좋았습니다. 시설도 잘 갖추어져 있어 편안하게 지낼 수 있었고, 다음에는 친구들과 함께 다시 방문하고 싶습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (28,'LOCATION','석촌호수 서호',37.5076807262772,127.099112837006,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (29,'IMAGE','/dummy-images/Dummy_Img(29).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (29,'TEXT','주말에 방문한 전통 시장입니다. 다양한 먹거리가 가득하고, 상인분들의 친절한 서비스가 인상적이었습니다. 특히 길거리 음식이 맛있어서 여러 가지를 시도해보았는데 모두 만족스러웠습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (29,'LOCATION','롯데월드 어드벤처',37.51113059993883,127.09811980036908,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (30,'IMAGE','/dummy-images/Dummy_Img(30).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (30,'TEXT','부산의 한적한 바닷가를 산책했습니다. 시원한 바닷바람과 함께 여유로운 시간을 보낼 수 있어 좋았습니다. 주변에 카페도 있어 음료를 즐기며 바다를 감상할 수 있어 힐링이 되었습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (30,'LOCATION','압구정로데오거리',37.5267558230172,127.039152029523,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (31,'IMAGE','/dummy-images/Dummy_Img(31).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (31,'TEXT','서울에서 최근 다녀온 맛집입니다. 내부 인테리어도 깔끔하고 분위기가 아늑해 식사 내내 편안했습니다. 특히 대표 메뉴인 스테이크는 육즙이 살아있고 맛이 풍부했습니다. 다음에 친구와 함께 다시 방문하고 싶네요.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (31,'LOCATION','용가회전훠궈 강남점',37.5013919194497,127.024909582192,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (32,'IMAGE','/dummy-images/Dummy_Img(32).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (32,'LOCATION','하이디라오 강남점',37.502564150766105,127.02480140187946,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (32,'TEXT','이번 주말에 다녀온 카페 후기입니다. 인테리어가 아기자기하고 포토존이 많아 사진 찍기에 좋습니다. 커피 맛도 훌륭하며, 디저트 메뉴도 추천할 만합니다. 친구들과 여유롭게 시간을 보내기에 딱 좋습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (33,'IMAGE','/dummy-images/Dummy_Img(33).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (33,'LOCATION','CGV 강남',37.5016573944824,127.026391177132,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (33,'TEXT','강릉 바닷가 근처의 숨은 맛집을 다녀왔습니다. 신선한 해산물 요리가 일품이며, 바다를 바라보며 식사할 수 있어 힐링됩니다. 위치가 조금 외진 곳이지만 충분히 방문할 가치가 있으며, 다음 여행에도 꼭 들르고 싶은 곳입니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (34,'IMAGE','/dummy-images/Dummy_Img(34).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (34,'LOCATION','롯데시네마 월드타워',37.51398362815245,127.1049339288905,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (34,'TEXT','데이트하기 좋은 예쁜 공원을 다녀왔습니다. 산책로가 잘 정비되어 있고 곳곳에 벤치와 포토존이 있어 여유롭게 즐길 수 있습니다. 특히 일몰 시간대에 방문하면 풍경이 더욱 아름다워 사진 찍기에도 적합합니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (35,'IMAGE','/dummy-images/Dummy_Img(35).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (35,'LOCATION','샤로수길',37.4785646095049,126.955677012972,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (35,'TEXT','부산 여행 중 다녀온 해산물 맛집입니다. 신선한 재료와 푸짐한 양으로 만족스러웠습니다. 특히 해물파전과 회가 인기 메뉴로 맛있으며, 내부 분위기도 아늑해 친구 또는 연인과 방문하기 좋습니다. 재방문 의사도 충분합니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (36,'IMAGE','/dummy-images/Dummy_Img(36).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (36,'LOCATION','국립중앙박물관',37.523846812103436,126.98020301886912,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (36,'TEXT','서울의 한적한 골목에 위치한 작은 카페를 방문했습니다. 커피와 디저트 모두 훌륭했고, 무엇보다 조용한 분위기에서 독서를 즐기기에 최적의 장소였습니다. 혼자만의 시간을 보내기에 완벽한 곳이었습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (37,'IMAGE','/dummy-images/Dummy_Img(37).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (37,'LOCATION','파파존스 신림점',37.480509094258906,126.90874908997151,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (37,'TEXT','주말에 가족과 함께 다녀온 전통 찻집입니다. 고즈넉한 분위기와 함께 전통 다과를 즐길 수 있어 좋았습니다. 특히 차 종류가 다양하고, 직원분들의 서비스도 친절하여 기분 좋은 시간을 보냈습니다.',null,null,2);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (38,'IMAGE','/dummy-images/Dummy_Img(38).jpg',null,null,1);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (38,'LOCATION','놀숲 강남역점',37.50098307994714,127.02796516792077,3);
Insert into POST_CONTENT_TBL (POST_SEQ,TYPE,CONTENT,LATITUDE,LONGITUDE,ORDER_NUM) values (38,'TEXT','서울 근교에 위치한 캠핑장에 다녀왔습니다. 자연 속에서 힐링하며 바베큐를 즐길 수 있어 좋았습니다. 시설도 잘 갖추어져 있어 편안하게 지낼 수 있었고, 다음에는 친구들과 함께 다시 방문하고 싶습니다.',null,null,2);

-- =========================================
-- COMMENT_TBL 임시 데이터
-- =========================================
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (11, 12, '정말 유익한 게시글이에요! 도움이 많이 되네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (2, 34, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (23, 8, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (4, 33, '정말 유익한 게시글이에요! 도움이 많이 되네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (7, 13, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (25, 3, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (14, 22, '정말 유익한 게시글이에요! 도움이 많이 되네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (2, 18, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (21, 20, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (20, 15, '질문이 있는데, 혹시 예제를 더 추가해주실 수 있나요?');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (20, 11, '정말 유익한 게시글이에요! 도움이 많이 되네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (13, 32, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (20, 5, '좋아요! 다음 글도 기대됩니다.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (22, 7, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (23, 12, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (30, 27, '좋아요! 다음 글도 기대됩니다.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (28, 15, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (27, 16, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (17, 24, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (32, 14, '정말 유익한 게시글이에요! 도움이 많이 되네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (11, 1, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (30, 38, '질문이 있는데, 혹시 예제를 더 추가해주실 수 있나요?');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (3, 37, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (36, 14, '좋아요! 다음 글도 기대됩니다.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (17, 21, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (4, 14, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (10, 36, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (33, 35, '정말 유익한 게시글이에요! 도움이 많이 되네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (17, 20, '질문이 있는데, 혹시 예제를 더 추가해주실 수 있나요?');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (4, 20, '좋아요! 다음 글도 기대됩니다.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (18, 32, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (16, 8, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (18, 4, '정말 유익한 게시글이에요! 도움이 많이 되네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (30, 5, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (35, 7, '좋아요! 다음 글도 기대됩니다.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (19, 14, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (8, 26, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (16, 25, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (16, 7, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (30, 21, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (4, 26, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (13, 34, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (1, 15, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (17, 4, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (32, 21, '정말 유익한 게시글이에요! 도움이 많이 되네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (20, 22, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (1, 16, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (8, 30, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (29, 24, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (25, 37, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (19, 2, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (21, 21, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (26, 15, '정말 유익한 게시글이에요! 도움이 많이 되네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (21, 11, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (13, 8, '질문이 있는데, 혹시 예제를 더 추가해주실 수 있나요?');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (4, 11, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (21, 25, '좋아요! 다음 글도 기대됩니다.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (11, 1, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (34, 22, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (30, 27, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (19, 35, '질문이 있는데, 혹시 예제를 더 추가해주실 수 있나요?');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (14, 12, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (21, 32, '질문이 있는데, 혹시 예제를 더 추가해주실 수 있나요?');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (30, 12, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (31, 35, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (19, 32, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (12, 38, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (13, 4, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (1, 28, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (1, 19, '좋아요! 다음 글도 기대됩니다.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (3, 27, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (2, 5, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (23, 3, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (15, 3, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (6, 19, '질문이 있는데, 혹시 예제를 더 추가해주실 수 있나요?');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (32, 37, '좋아요! 다음 글도 기대됩니다.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (26, 20, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (17, 22, '정말 유익한 게시글이에요! 도움이 많이 되네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (22, 16, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (36, 17, '정말 유익한 게시글이에요! 도움이 많이 되네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (6, 35, '좋아요! 다음 글도 기대됩니다.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (19, 22, '좋아요! 다음 글도 기대됩니다.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (32, 11, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (24, 5, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (9, 17, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (19, 26, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (23, 28, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (2, 11, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (25, 21, '정말 유익한 게시글이에요! 도움이 많이 되네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (5, 31, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (9, 35, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (2, 16, '정말 유익한 게시글이에요! 도움이 많이 되네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (27, 27, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (6, 27, '공감합니다! 저도 같은 경험이 있어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (35, 34, '내용이 알차고 이해하기 쉬워요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (7, 28, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (35, 15, '이 부분은 조금 더 자세히 설명해주면 좋겠어요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (24, 23, '와, 사진이 정말 멋지네요.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (32, 27, '좋아요! 다음 글도 기대됩니다.');
INSERT INTO COMMENT_TBL (post_seq, user_seq, content) VALUES (28, 27, '좋아요! 다음 글도 기대됩니다.');

-- =========================================
-- FAVORITE_TBL 임시 데이터
-- =========================================
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (33, 4);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (27, 4);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (36, 20);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (11, 16);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (35, 24);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (34, 33);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (2, 28);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (2, 2);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (22, 25);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (14, 18);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (7, 16);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (9, 14);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (25, 22);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (34, 31);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (19, 11);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (37, 8);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (35, 17);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (28, 3);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (32, 13);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (30, 23);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (33, 29);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (19, 36);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (16, 26);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (33, 1);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (21, 23);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (12, 31);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (20, 5);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (16, 32);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (23, 23);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (35, 26);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (23, 32);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (11, 3);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (4, 11);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (27, 11);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (15, 21);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (27, 26);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (7, 26);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (7, 14);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (26, 26);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (28, 11);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (29, 32);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (11, 5);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (33, 34);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (8, 9);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (36, 12);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (5, 33);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (26, 22);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (19, 38);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (7, 33);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (9, 9);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (20, 33);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (17, 25);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (24, 27);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (28, 16);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (22, 5);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (4, 30);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (6, 35);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (16, 8);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (15, 11);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (29, 8);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (35, 22);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (36, 34);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (13, 12);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (25, 25);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (21, 24);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (20, 7);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (26, 13);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (29, 12);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (13, 23);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (19, 7);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (21, 38);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (32, 27);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (17, 6);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (7, 3);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (21, 7);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (30, 15);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (18, 33);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (35, 38);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (37, 33);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (12, 33);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (12, 3);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (6, 25);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (29, 13);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (36, 15);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (4, 15);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (27, 34);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (19, 22);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (33, 28);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (7, 13);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (30, 5);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (10, 18);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (13, 4);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (27, 25);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (1, 13);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (11, 15);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (2, 10);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (34, 37);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (24, 26);
INSERT INTO FAVORITE_TBL (post_seq, user_seq) VALUES (28, 21);

-- =========================================
-- LIKE_TBL 임시 데이터
-- =========================================
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (34, 36);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (33, 16);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (14, 37);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (20, 7);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (25, 1);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (9, 29);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (16, 38);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (6, 13);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (5, 5);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (28, 7);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (11, 7);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (20, 21);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (26, 4);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (35, 38);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (18, 26);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (10, 7);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (13, 35);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (6, 14);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (15, 5);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (24, 7);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (18, 9);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (14, 28);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (36, 21);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (21, 8);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (5, 27);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (38, 9);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (20, 8);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (12, 8);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (11, 6);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (31, 9);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (20, 30);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (15, 2);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (13, 34);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (1, 32);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (7, 6);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (9, 27);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (25, 3);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (35, 31);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (18, 20);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (35, 17);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (22, 31);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (14, 13);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (33, 17);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (31, 26);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (14, 31);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (35, 14);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (17, 28);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (17, 8);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (34, 27);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (13, 24);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (22, 14);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (37, 34);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (5, 10);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (12, 33);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (5, 9);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (38, 3);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (7, 16);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (8, 15);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (8, 38);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (12, 5);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (9, 5);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (33, 9);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (15, 24);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (22, 10);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (17, 7);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (26, 26);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (26, 11);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (2, 15);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (19, 15);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (28, 35);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (12, 11);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (20, 3);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (7, 36);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (37, 12);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (34, 19);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (33, 11);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (24, 14);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (1, 16);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (37, 8);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (29, 33);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (8, 7);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (2, 22);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (25, 14);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (20, 27);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (23, 13);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (36, 24);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (1, 12);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (14, 17);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (31, 30);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (28, 5);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (14, 25);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (13, 30);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (17, 24);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (1, 24);
INSERT INTO LIKE_TBL (post_seq, user_seq) VALUES (1, 15);

commit;